version: "3"

tasks:
  ko:
    cmds:
      - podman run --rm -it
        -v $PWD:/work:Z
        --workdir=/work
        -e KO_DOCKER_REPO=gitea.nulo.in/nulo/ddnser
        -v ~/.docker/:/docker-config:Z,ro
        -e DOCKER_CONFIG=/docker-config
            cgr.dev/chainguard/ko build --bare .
